<?xml version="1.0" encoding="utf-8"?><testsuite errors="0" failures="0" name="pytest" skipped="0" tests="4" time="0.033"><testcase classname="test_library_app_pytest.TestLibraryApp" file="test_library_app_pytest.py" line="16" name="test_parse_user_input_book" time="0.002"><system-out>One of the documents in the list is not a recognized type. Document type: Failure; With key: Oladele2019
</system-out></testcase><testcase classname="test_library_app_pytest.TestLibraryApp" file="test_library_app_pytest.py" line="23" name="test_parse_user_input_journal" time="0.001"><system-out>One of the documents in the list is not a recognized type. Document type: Failure; With key: Oladele2019
</system-out></testcase><testcase classname="test_library_app_pytest.TestLibraryApp" file="test_library_app_pytest.py" line="30" name="test_parse_user_input_conference" time="0.001"><system-out>One of the documents in the list is not a recognized type. Document type: Failure; With key: Oladele2019
</system-out></testcase><testcase classname="test_library_app_pytest.TestLibraryApp" file="test_library_app_pytest.py" line="37" name="test_parse_user_input_invalid_key" time="0.001"><system-out>One of the documents in the list is not a recognized type. Document type: Failure; With key: Oladele2019
</system-out></testcase></testsuite>